"use client";
import { useRef, useState } from "react";
import type { FormEvent } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { api, workspacePath } from "@/lib/client-api";
import { REVIEW_GATES } from "@/lib/delivery";
import type { AgentConnection, DeliveryProject, Reviewers } from "@/lib/delivery";
import type { Member } from "@/lib/domain";
import { AGENT_ROLE_LABELS } from "@/lib/agents";
import type { AgentBindingSummary } from "@/lib/agents";
import { Choice } from "./controls";

const gateLabels = { requirements: "BA requirements approval", architecture: "Architecture and assignment", engineering: "Engineering and peer review", qa: "QA acceptance", uat: "Business UAT approval", release: "Release authorization and closure" };
const reasonError = (e: unknown) => e instanceof Error ? e.message : "The decision could not be saved.";
function useReceipt() { const receipt = useRef({ signature: "", id: "" }); return (input: unknown) => { const signature = JSON.stringify(input); if (receipt.current.signature !== signature) receipt.current = { signature, id: crypto.randomUUID() }; return receipt.current.id; }; }
export function DeliveryResponsibilities({ workspaceId, projectId, configuration, members, userId, admin, onSaved }: { workspaceId: string; projectId: string; configuration: DeliveryProject | null; members: Member[]; userId: string; admin: boolean; onSaved: () => void }) {
  const [reviewers, setReviewers] = useState<Reviewers>(() => configuration?.reviewers ?? Object.fromEntries(REVIEW_GATES.map(g => [g, userId])) as Reviewers); const [reason, setReason] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const lock = useRef(false); const receipt = useReceipt();
  async function save(event: FormEvent) { event.preventDefault(); if (lock.current) return; lock.current = true; setBusy(true); setError(""); const body = { expected_version: configuration?.version ?? 0, reviewers, reason }; try { await api(workspacePath(`projects/${projectId}/delivery`, workspaceId), { method: "POST", body: { ...body, request_id: receipt(body) } }); onSaved(); } catch (e) { setError(reasonError(e)); } finally { setBusy(false); lock.current = false; } }
  return <form className="delivery-setup" onSubmit={save}><h3>{configuration ? "Accountable humans" : "First, name the accountable humans"}</h3><p className="muted">Each gate has a named reviewer. One person can cover several responsibilities in a small team. Every agent still has its own operator.</p><div className="delivery-reviewers">{REVIEW_GATES.map(gate => <Label key={gate}>{gateLabels[gate]}<Choice label={gateLabels[gate]} value={reviewers[gate]} disabled={!admin || busy} onChange={value => setReviewers(v => ({ ...v, [gate]: value }))} options={members.filter(m => !["requirements", "architecture"].includes(gate) || m.role === "admin").map(m => ({ value: m.user_id, label: m.name }))} /></Label>)}</div>{admin && <><Label htmlFor="delivery-responsibility-reason">Reason for this setup<Input id="delivery-responsibility-reason" value={reason} onChange={e => setReason(e.target.value)} maxLength={1000} required disabled={busy} /></Label><Button type="submit" disabled={busy || !reason.trim()}>{busy ? "Saving…" : configuration ? "Save human responsibilities" : "Initialize delivery"}</Button></>}{!admin && !configuration && <p>A workspace admin must initialize these responsibilities before agent work begins.</p>}{error && <p role="alert" className="error-box">{error}</p>}</form>;
}
export function DiscoveryForm({ workspaceId, projectId, configuration, userId, onSaved }: { workspaceId: string; projectId: string; configuration: DeliveryProject; userId: string; onSaved: () => void }) {
  const choices = [{ value: "requirements", label: "BA · requirements", owner: configuration.reviewers.requirements }, { value: "architecture", label: "Architect · design and ticket plan", owner: configuration.reviewers.architecture }].filter(v => v.owner === userId);
  const [kind, setKind] = useState(choices[0]?.value ?? "requirements"); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [acceptance, setAcceptance] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const lock = useRef(false); const receipt = useReceipt();
  async function create(event: FormEvent) { event.preventDefault(); if (lock.current) return; lock.current = true; setBusy(true); setError(""); const body = { kind, title, description, acceptance: acceptance.split("\n").map(s => s.trim()).filter(Boolean) }; try { await api(workspacePath(`projects/${projectId}/delivery/discovery`, workspaceId), { method: "POST", body: { ...body, request_id: receipt(body) } }); onSaved(); } catch (e) { setError(reasonError(e)); } finally { setBusy(false); lock.current = false; } }
  return <form className="delivery-setup" onSubmit={create}><h3>Create a discovery task</h3><Choice label="Discovery role" value={kind} onChange={setKind} options={choices} disabled={busy} /><Label htmlFor="discovery-title">Title<Input id="discovery-title" required maxLength={200} value={title} onChange={e => setTitle(e.target.value)} disabled={busy} /></Label><Label htmlFor="discovery-description">What should the agent investigate?<Textarea id="discovery-description" required maxLength={6000} value={description} onChange={e => setDescription(e.target.value)} disabled={busy} /></Label><Label htmlFor="discovery-acceptance">Acceptance criteria · one per line<Textarea id="discovery-acceptance" required maxLength={8000} value={acceptance} onChange={e => setAcceptance(e.target.value)} disabled={busy} /></Label><Button type="submit" disabled={busy}>{busy ? "Creating…" : "Create for manual assignment"}</Button>{error && <p role="alert" className="error-box">{error}</p>}</form>;
}
export function DeliveryConnections({ workspaceId, projectId, userId, bindings, connections, onSaved }: { workspaceId: string; projectId: string; userId: string; bindings: AgentBindingSummary[]; connections: AgentConnection[]; onSaved: () => void }) {
  const eligible = bindings.filter(b => b.operator_id === userId && b.state === "initialized" && b.template_current && b.operator_available);
  const [bindingId, setBindingId] = useState(eligible[0]?.id ?? ""); const [name, setName] = useState(""); const [accepted, setAccepted] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [setup, setSetup] = useState<AgentConnection | null>(null); const [revoke, setRevoke] = useState<AgentConnection | null>(null); const [reason, setReason] = useState(""); const lock = useRef(false); const receipt = useReceipt();
  const binding = eligible.find(b => b.id === bindingId) ?? eligible[0];
  async function enroll(event: FormEvent) {
    event.preventDefault(); if (lock.current || !binding) return; lock.current = true; setBusy(true); setError("");
    const body = { binding_id: binding.id, binding_version: binding.version, template_hash: binding.template_hash, name, accept_responsibility: accepted };
    try { const c = await api<AgentConnection>(workspacePath(`projects/${projectId}/delivery/connections`, workspaceId), { method: "POST", body: { ...body, request_id: receipt(body) } }); setSetup(c); setName(""); setAccepted(false); onSaved(); } catch (e) { setError(reasonError(e)); } finally { setBusy(false); lock.current = false; }
  }
  async function confirmRevoke() {
    if (!revoke || lock.current) return; lock.current = true; setBusy(true); setError(""); const body = { expected_version: revoke.version, reason };
    try { await api(workspacePath(`projects/${projectId}/delivery/connections/${revoke.id}/revoke`, workspaceId), { method: "POST", body: { ...body, request_id: receipt(body) } }); setRevoke(null); setReason(""); setSetup(null); onSaved(); } catch (e) { setError(reasonError(e)); } finally { setBusy(false); lock.current = false; }
  }
  const command = setup && setup.client_id && setup.companion_client_id ? `node scripts/stride-agent.mjs login --site ${typeof window === "undefined" ? "https://your-stride-site" : window.location.origin} --connection ${setup.id} --client-id ${setup.client_id} --companion-client-id ${setup.companion_client_id}` : null;
  return <div className="delivery-connections"><div className="delivery-setup"><h3>Connect an attended agent</h3><p>Choose an approved role you operate. The companion works with any IDE or CLI that supports local MCP servers.</p>{eligible.length ? <form className="space-y-4" onSubmit={enroll}><Choice label="Your approved agent role" value={binding?.id ?? ""} onChange={setBindingId} options={eligible.map(b => ({ value: b.id, label: `${b.alias} · ${AGENT_ROLE_LABELS[b.role_id]}` }))} disabled={busy} /><Label htmlFor="connection-name">Machine name<Input id="connection-name" required maxLength={80} placeholder="Work laptop · Codex" value={name} onChange={e => setName(e.target.value)} disabled={busy} /></Label><Label className="flex items-start gap-3"><input type="checkbox" checked={accepted} onChange={e => setAccepted(e.target.checked)} disabled={busy} />I reviewed this role and accept responsibility for the new connection.</Label><Button type="submit" disabled={busy || !accepted || !binding}>{busy ? "Enrolling…" : "Enroll connection"}</Button></form> : <p className="muted">Accept a role in Team and agents first. Only its named human operator can enroll a connection.</p>}</div>
    {error && <p role="alert" className="error-box">{error}</p>}
    {setup && <div className="delivery-setup"><h3>Finish on {setup.name}</h3>{command ? <><p>In your Stride checkout, run <code>npm ci</code>, then:</p><pre className="agent-prompt">{command}</pre><p>Approve the agent and companion access in your browser. Add this local MCP server to your IDE:</p><pre className="agent-prompt">{JSON.stringify({ mcpServers: { stride: { command: "node", args: ["/absolute/path/to/stride/scripts/stride-agent.mjs", "mcp", "--connection", setup.id] } } }, null, 2)}</pre><p>For each assigned task, keep this companion running in the task’s clean checkout:</p><pre className="agent-prompt">{`node /absolute/path/to/stride/scripts/stride-agent.mjs watch --connection ${setup.id} --ticket TICKET_ID`}</pre><p className="muted">The IDE agent reads its role and initializes. You review and authorize the prepared packet in Stride, then ask the agent to claim it. Credentials stay in the companion’s private local file.</p></> : <p>Client registration is incomplete. Retry enrollment with the same details to finish setup.</p>}</div>}
    <div className="agent-grid">{connections.map(c => <article className="agent-card" key={c.id}><h3>{c.name}</h3><p>{c.state === "revoked" ? "Revoked" : c.lease_until && c.lease_until > new Date().toISOString() ? "Companion online" : "Companion offline"} · {c.initialized_at ? "Agent initialized" : "Agent not initialized"}</p><p className="agent-identity">Profile <code>{c.profile_id}</code></p><p className="agent-identity">Connection <code>{c.id}</code></p><div className="inline-actions"><Button variant="outline" size="sm" disabled={c.state === "revoked" || busy} onClick={() => setSetup(c)}>Setup instructions</Button><Button variant="ghost" size="sm" disabled={c.state === "revoked" || busy} onClick={() => { setRevoke(c); setReason(""); }}>Revoke</Button></div></article>)}</div>
    {revoke && <section className="delivery-setup" aria-label="Confirm connection revocation"><h3>Revoke {revoke.name}?</h3><p>Stride will reject further actions and end its run authority. Its human operator must stop any local process.</p><Label htmlFor="revoke-reason">Reason<Input id="revoke-reason" value={reason} onChange={e => setReason(e.target.value)} maxLength={1000} disabled={busy} /></Label><div className="inline-actions"><Button variant="destructive" disabled={busy || !reason.trim()} onClick={() => void confirmRevoke()}>Revoke connection</Button><Button variant="outline" disabled={busy} onClick={() => setRevoke(null)}>Keep connection</Button></div></section>}
  </div>;
}
