"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { api, workspacePath } from "@/lib/client-api";
import { AGENT_ROLE_LABELS } from "@/lib/agents";
import type { AgentBindingSummary } from "@/lib/agents";
import { roleGate } from "@/lib/delivery";
import type { AgentConnection, DeliveryProject, DeliveryTicket, WorkPacket } from "@/lib/delivery";
import type { Member } from "@/lib/domain";
import { Choice } from "./controls";

type Detail = { ticket: DeliveryTicket; packet: { id: string; hash: string; payload: WorkPacket } | null; packet_error: string | null; report_hash: string | null; configuration: DeliveryProject; attempt: { state: string; lease_until: string | null; grant_expires: string; started_at: string | null } | null };
type AuditEvent = { id: string; sequence: number; actor_kind: string; actor_id: string; operator_id: string | null; action: string; reason: string; created_at: string };
type Props = { workspaceId: string; projectId: string; ticketId: string; userId: string; members: Member[]; bindings: AgentBindingSummary[]; connections: AgentConnection[]; onClose: () => void; onSaved: () => void };
export function DeliveryDialog({ workspaceId, projectId, ticketId, userId, members, bindings, connections, onClose, onSaved }: Props) {
  const [detail, setDetail] = useState<Detail | null>(null); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false); const [discard, setDiscard] = useState(false);
  const [bindingId, setBindingId] = useState(""); const [connectionId, setConnectionId] = useState(""); const [reason, setReason] = useState(""); const [reviewed, setReviewed] = useState(false);
  const [environment, setEnvironment] = useState(""); const [artifact, setArtifact] = useState(""); const [configuration, setConfiguration] = useState(""); const [migration, setMigration] = useState(""); const [recovery, setRecovery] = useState("");
  const [events, setEvents] = useState<AuditEvent[]>([]); const [moreEvents, setMoreEvents] = useState(false); const [showHistory, setShowHistory] = useState(false);
  const lock = useRef(false); const request = useRef({ signature: "", id: "" }); const controller = useRef<AbortController | null>(null);
  const base = `projects/${encodeURIComponent(projectId)}/delivery/tickets/${encodeURIComponent(ticketId)}`;
  const load = useCallback(async () => { controller.current?.abort(); const c = new AbortController(); controller.current = c; try { const d = await api<Detail>(workspacePath(base, workspaceId), { signal: c.signal }); if (!c.signal.aborted) { setDetail(d); setError(""); } } catch (e) { if (!c.signal.aborted) setError(e instanceof Error ? e.message : "This work could not be loaded."); } }, [base, workspaceId]);
  useEffect(() => { void load(); return () => controller.current?.abort(); }, [load]);
  async function act(action: string, values: Record<string, unknown>) {
    if (!detail || lock.current) return; lock.current = true; setBusy(true); setError(""); setNotice("");
    const body = { expected_version: detail.ticket.version, reason, ...values }; const signature = JSON.stringify({ action, body });
    if (request.current.signature !== signature) request.current = { signature, id: crypto.randomUUID() };
    try { await api(workspacePath(`${base}/${action}`, workspaceId), { method: "POST", body: { ...body, request_id: request.current.id } }); setReason(""); setReviewed(false); setNotice("Decision recorded. The next step is shown below."); await load(); onSaved(); }
    catch (e) { setError(e instanceof Error ? e.message : "The decision could not be saved. Your draft is preserved."); } finally { setBusy(false); lock.current = false; }
  }
  async function history(append = false) {
    if (lock.current) return; lock.current = true; setBusy(true); setError("");
    try { const page = await api<{ events: AuditEvent[]; has_more: boolean }>(`${workspacePath(`${base}/events`, workspaceId)}&after=${append ? events.at(-1)?.sequence ?? 0 : 0}`); setEvents(v => append ? [...v, ...page.events] : page.events); setMoreEvents(page.has_more); setShowHistory(true); } catch (e) { setError(e instanceof Error ? e.message : "History could not be loaded."); } finally { setBusy(false); lock.current = false; }
  }
  const t = detail?.ticket; const cfg = detail?.configuration; const packet = detail?.packet?.payload; const report = t?.payload.report;
  const assigned = bindings.find(b => b.id === t?.binding_id); const roleChoices = bindings.filter(b => b.role_id === t?.role_id && b.state === "initialized" && b.template_current && b.operator_available);
  const ownConnections = connections.filter(c => c.binding_id === t?.binding_id && c.state === "active" && c.operator_id === userId);
  const selectedConnection = ownConnections.find(c => c.id === connectionId);
  const canAssign = !!t && !!cfg && [cfg.reviewers[t.kind === "requirements" ? "requirements" : "architecture"], cfg.reviewers[roleGate(t.role_id)]].includes(userId);
  const canReview = !!t && cfg?.reviewers[roleGate(t.role_id)] === userId;
  const canStop = assigned?.operator_id === userId || !!cfg && Object.values(cfg.reviewers).includes(userId);
  const ready = !!reason.trim() && reviewed && !busy;
  const close = () => { if (busy) return; if (reason || environment || artifact || migration || recovery) setDiscard(true); else onClose(); };
  const name = (id: string) => members.find(m => m.user_id === id)?.name ?? "Former member";
  return <><Dialog open onOpenChange={open => { if (!open) close(); }}><DialogContent className="context-editor-dialog context-three-pane-dialog delivery-dialog"><DialogHeader><DialogTitle>{t?.title ?? "Review agent work"}</DialogTitle><DialogDescription>Review the shared context, agent evidence and the next human decision.</DialogDescription></DialogHeader>
    {error && <div role="alert" className="error-box"><p>{error}</p><Button variant="outline" disabled={busy} onClick={() => void load()}>Refresh current work</Button></div>}{notice && <p role="status" className="agent-notice">{notice}</p>}
    {!detail && !error && <p role="status">Loading work and its context…</p>}
    {detail && t && cfg && <div className="context-three-pane">
      <section className="context-pane context-baseline"><h3>Task and shared context</h3><span className={`delivery-phase delivery-phase-${t.phase}`}>{t.phase.replaceAll("_", " ")}</span><p><strong>{AGENT_ROLE_LABELS[t.role_id]}</strong></p><p>Human reviewer: {name(cfg.reviewers[roleGate(t.role_id)])}</p>{assigned && <p>Assigned to {assigned.alias}<br />Operator: {assigned.operator_name}</p>}<p className="agent-identity">Ticket <code>{t.id}</code></p><h4>Acceptance criteria</h4><ul className="delivery-bullets">{t.payload.acceptance.map((a, i) => <li key={i}>{a}</li>)}</ul><h4>To do</h4><ol className="delivery-bullets">{t.payload.todo.map((a, i) => <li key={i}>{a}</li>)}</ol>
        {!!t.payload.depends_on.length && <p className="muted">Waiting on {t.payload.depends_on.length} accepted delivery outcome{t.payload.depends_on.length === 1 ? "" : "s"}.</p>}
        {packet && <><h4>Approved context</h4>{packet.context.length ? packet.context.map(d => <details key={d.document_id}><summary>{d.title} · v{d.version}</summary><p className="brief-body">{d.body}</p><small>Approved by {name(d.approved_by)}</small></details>) : <p className="muted">Discovery begins with the human’s task brief. No baseline is approved yet.</p>}<h4>Repository</h4><p>{packet.repository?.full_name ?? "Document discovery · repository not connected"}</p>{packet.repository && <code className="agent-identity">{packet.repository.commit}</code>}<p className="muted">Read: {packet.read_paths.join(", ") || "No repository files"}<br />Write: {packet.write_paths.join(", ") || "No repository files"}</p></>}
        {detail.packet_error && <p role="status" className="error-box">{detail.packet_error}</p>}
        {t.payload.candidate && <><h4>Candidate under review</h4><p>PR #{t.payload.candidate.pull_request}</p><code className="agent-identity">{t.payload.candidate.commit}</code></>}
      </section>
      <section className="context-pane context-draft"><h3>Agent work and evidence</h3>{report ? <><p className="delivery-phase">Reported outcome: {report.outcome}</p><p className="brief-body">{report.summary}</p><p className="muted">Agent-reported evidence. Stride verifies GitHub candidate and check results before human acceptance.</p><p className="brief-body">{report.evidence.summary}</p>{report.evidence.checks.map((c, i) => <details key={i}><summary>{c.name} · {c.result}</summary><p className="brief-body">{c.details}</p></details>)}{report.findings.map((f, i) => <article className="delivery-finding" key={i}><h4>{f.title}</h4><p>Reproduce: {f.reproduction}</p><p>Expected: {f.expected}</p><p>Actual: {f.actual}</p><small>Proposed owner: {f.route}</small></article>)}{report.requirements.map((d, i) => <details key={i} open><summary>{d.title} · proposed {t.kind === "requirements" ? "requirement" : "design"}</summary><p className="brief-body">{d.body}</p></details>)}{!!report.plan.length && <><h4>Proposed delivery tickets</h4><p className="muted">Acceptance creates these tickets. You assign agent profiles afterward.</p>{report.plan.map(p => <details key={p.key}><summary>{p.key} · {p.title}</summary><p>{p.description}</p><ul className="delivery-bullets">{p.acceptance.map((a, i) => <li key={i}>{a}</li>)}</ul><p>Read: {p.read_paths.join(", ")}<br />Write: {p.write_paths.join(", ") || "None"}<br />Dependencies: {p.depends_on.join(", ") || "None"}</p></details>)}</>}<p><strong>Proposed next action:</strong> {report.next_action}</p></> : <p className="muted">The agent’s report appears here after it claims an approved attempt and submits its work.</p>}
        {t.payload.last_checkpoint && <details open><summary>Last shared checkpoint</summary><p>{t.payload.last_checkpoint.summary}</p><ul className="delivery-bullets">{t.payload.last_checkpoint.next_steps.map((s, i) => <li key={i}>{s}</li>)}</ul></details>}
        {packet && <details><summary>Read the exact role prompt and work packet</summary><pre className="agent-prompt">{packet.prompt}</pre><ul className="delivery-bullets">{packet.exclusions.map((e, i) => <li key={i}>{e}</li>)}</ul><p className="agent-identity">Packet fingerprint <code>{detail.packet?.hash}</code></p></details>}
        <Button variant="outline" disabled={busy} onClick={() => void history()}>View timestamped history</Button>{showHistory && <ol className="brief-history">{events.map(e => <li key={e.id}><strong>{e.action.replaceAll("_", " ")}</strong><p>{e.actor_kind === "human" ? name(e.actor_id) : e.actor_kind === "agent" ? `${bindings.find(b => b.profile_id === e.actor_id)?.alias ?? "Agent"} · operator ${name(e.operator_id ?? "")}` : "Coordinator"} · <time dateTime={e.created_at}>{new Date(e.created_at).toLocaleString()}</time></p><p>{e.reason}</p></li>)}</ol>}{showHistory && moreEvents && <Button variant="outline" disabled={busy} onClick={() => void history(true)}>More events</Button>}
      </section>
      <section className="context-pane context-review"><h3>Human decision</h3>{detail.attempt && <p className="muted">Attempt: {detail.attempt.state}{detail.attempt.lease_until ? ` · lease until ${new Date(detail.attempt.lease_until).toLocaleTimeString()}` : ""}</p>}
        {["accepted", "cancelled"].includes(t.phase) ? <p>{t.phase === "accepted" ? "This outcome is accepted. Create a follow-up ticket for any new change." : "This delivery was cancelled. Its history remains available."}</p> : <>
          <Label htmlFor="delivery-decision-reason">Decision or feedback<Textarea id="delivery-decision-reason" value={reason} onChange={e => setReason(e.target.value)} maxLength={1000} disabled={busy} placeholder="What did you review, and what should happen next?" /></Label>
          {canAssign && ["created", "assigned", "start_approved", "in_progress"].includes(t.phase) && <><Choice label="Assign agent role" value={bindingId} onChange={setBindingId} options={[{ value: "", label: "Choose an available role" }, ...roleChoices.map(b => ({ value: b.id, label: `${b.alias} · ${b.operator_name}` }))]} disabled={busy} /><Button variant="outline" disabled={!bindingId || !reason.trim() || busy} onClick={() => void act("assign", { binding_id: bindingId })}>Assign and prepare packet</Button>{!roleChoices.length && <p className="muted">Initialize this role in Team and agents first.</p>}</>}
          {t.phase === "assigned" && assigned?.operator_id === userId && <><Choice label="Connection to start" value={connectionId} onChange={setConnectionId} options={[{ value: "", label: "Choose your prepared connection" }, ...ownConnections.map(c => ({ value: c.id, label: c.name }))]} disabled={busy} />{selectedConnection && <p className="muted">{selectedConnection.prepared?.packet_id === detail.packet?.id ? "Companion prepared this packet." : "Run the companion watch command with this ticket ID."} Checkout facts are reported by your companion.</p>}<p>Authorize only this packet on the selected machine. Then ask your IDE agent to claim the task.</p></>}
          {t.phase === "in_review" && !canReview && <p>Waiting for {name(cfg.reviewers[roleGate(t.role_id)])} to review this report.</p>}
          {t.phase === "uat_authorization" && <p>QA passed human review. Identify the successful UAT deployment before assigning business testing.</p>}
          {t.phase === "release_authorization" && <p>UAT passed human review. Authorize the exact production candidate and its recovery plan.</p>}
          {((t.phase === "uat_authorization" && cfg.reviewers.uat === userId) || (t.phase === "release_authorization" && cfg.reviewers.release === userId)) && <><Label htmlFor="delivery-environment">Exact environment<Input id="delivery-environment" value={environment} onChange={e => setEnvironment(e.target.value)} maxLength={100} disabled={busy} /></Label><Label htmlFor="delivery-artifact">Artifact identifier<Input id="delivery-artifact" value={artifact} onChange={e => setArtifact(e.target.value)} maxLength={300} disabled={busy} /></Label>{t.phase === "release_authorization" && <><Label htmlFor="delivery-config">Configuration version<Input id="delivery-config" value={configuration} onChange={e => setConfiguration(e.target.value)} maxLength={300} disabled={busy} /></Label><Label htmlFor="delivery-migration">Migration plan<Textarea id="delivery-migration" value={migration} onChange={e => setMigration(e.target.value)} maxLength={2000} disabled={busy} /></Label><Label htmlFor="delivery-recovery">Recovery plan<Textarea id="delivery-recovery" value={recovery} onChange={e => setRecovery(e.target.value)} maxLength={2000} disabled={busy} /></Label></>}</>}
          <Label className="context-human-approval"><input type="checkbox" checked={reviewed} onChange={e => setReviewed(e.target.checked)} disabled={busy} />I reviewed the current scope, evidence and responsibility for this decision.</Label>
          {t.phase === "assigned" && assigned?.operator_id === userId && <Button disabled={!ready || !connectionId || !detail.packet} onClick={() => void act("start", { connection_id: connectionId, packet_hash: detail.packet?.hash, accept_start: true })}>Authorize this start</Button>}
          {t.phase === "in_review" && canReview && <><Button disabled={!ready || report?.outcome !== "pass"} onClick={() => void act("review", { decision: "accept", report_hash: detail.report_hash })}>{t.kind === "requirements" ? "Approve requirements baseline" : t.kind === "architecture" ? "Approve design and create tickets" : t.role_id === "release_operations" ? "Verify production and close" : "Accept report and advance"}</Button><Button variant="outline" disabled={!ready} onClick={() => void act("review", { decision: "return", report_hash: detail.report_hash })}>Return for rework</Button></>}
          {t.phase === "uat_authorization" && cfg.reviewers.uat === userId && <Button disabled={!ready || !environment || !artifact} onClick={() => void act("uat", { environment, artifact, accept_authorization: true })}>Verify deployment and authorize UAT</Button>}
          {t.phase === "release_authorization" && cfg.reviewers.release === userId && <Button disabled={!ready || !environment || !artifact || !configuration || !migration || !recovery} onClick={() => void act("release", { environment, artifact, configuration, migration, recovery, accept_authorization: true })}>Authorize production release</Button>}
          {t.phase === "replan_required" && <p>Ask the BA or architecture human to create a revised discovery task. Cancel this obsolete ticket after the replacement plan is accepted.</p>}
          {canStop && ["assigned", "start_approved", "in_progress"].includes(t.phase) && <Button variant="outline" disabled={!ready} onClick={() => void act("stop", { cancel_ticket: false })}>Pause attempt</Button>}
          {canStop && <Button variant="ghost" disabled={!ready} onClick={() => void act("stop", { cancel_ticket: true })}>Cancel ticket</Button>}
        </>}
      </section>
    </div>}
  </DialogContent></Dialog><AlertDialog open={discard} onOpenChange={setDiscard}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Discard your review draft?</AlertDialogTitle><AlertDialogDescription>Your unsaved decision text and environment details will be lost.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep reviewing</AlertDialogCancel><AlertDialogAction onClick={onClose}>Discard draft</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}
