import test from "node:test";
import assert from "node:assert/strict";
import { Pool } from "pg";
import { hashPassword } from "better-auth/crypto";
import { Repository } from "../lib/server/repository.ts";
import { PostgresDatabase } from "../lib/server/postgres-adapter.ts";
import { ProductivityRepository } from "../lib/server/productivity-repository.ts";
import { Invitations } from "../lib/server/invitations.ts";
import { Attachments } from "../lib/server/attachments.ts";
import { EmailOutbox } from "../lib/server/email.ts";
import { DEFAULT_PREFERENCES } from "../lib/productivity.ts";

const value = process.env.TEST_DATABASE_URL; const url = new URL(value ?? "");
if (!["127.0.0.1", "localhost"].includes(url.hostname) || url.pathname !== "/stride_test") throw new Error("Productivity integration tests require isolated stride_test");
test("Productivity release uses real PostgreSQL transactions and tenant constraints", async t => {
  const pool = new Pool({ connectionString: value, max: 4, statement_timeout: 10000 }); t.after(() => pool.end());
  const repo = new Repository(new PostgresDatabase(pool)); const service = new ProductivityRepository(repo); const suffix = crypto.randomUUID();
  const owner = { userId: `prod_${suffix}`, email: `prod_${suffix}@example.test`, displayName: "Productivity fixture" };
  const workspace = (await repo.bootstrap(owner)).workspaces[0].id; const project = (await repo.metadata(owner.userId, workspace)).projects[0].id;
  let task = await repo.createTask(owner.userId, workspace, { title: "Repeat", project_id: project, recurrence: "weekly", due_date: "2026-09-14" });
  const checklist = (await service.changeChecklist(owner.userId, workspace, task.id, null, { title: "Review" })).item!;
  await service.changeChecklist(owner.userId, workspace, task.id, checklist.id, { version: 1, completed: true });
  const completing = await Promise.allSettled([1, 2].map(() => repo.updateTask(owner.userId, workspace, task.id, { version: task.version, status: "done" })));
  assert.equal(completing.filter(result => result.status === "fulfilled").length, 1);
  const successors = await pool.query("SELECT id FROM tasks WHERE recurrence_parent_id=$1", [task.id]); assert.equal(successors.rowCount, 1);
  assert.equal((await service.checklist(owner.userId, workspace, successors.rows[0].id))[0].completed, 0);
  task = await repo.task(owner.userId, workspace, task.id);
  const other = await repo.createTask(owner.userId, workspace, { title: "Second", project_id: project });
  await assert.rejects(service.bulk(owner.userId, workspace, { tasks: [{ id: task.id, version: task.version }, { id: other.id, version: 99 }], changes: { priority: "high" } }), { status: 409 });
  assert.equal((await repo.task(owner.userId, workspace, task.id)).priority, "medium");
  const preference = await service.savePreferences(owner.userId, workspace, DEFAULT_PREFERENCES); assert.equal(preference.version, 1);
  await service.saveView(owner.userId, workspace, null, { name: "Today", filters: { due: "today" } });
  const template = await service.saveTemplate(owner.userId, workspace, null, { name: "Routine", task: { title: "Routine" }, checklist: ["Step"] });
  assert.equal((await service.useTemplate(owner.userId, workspace, template.id, { project_id: project })).checklist_total, 1);
  assert.ok((await service.workload(owner.userId, workspace))[0].open > 0);
  const invitations = new Invitations(repo, hashPassword); const invite = await invitations.create(owner.userId, workspace, { email: `invited_${suffix}@example.test` }); const token = invite.path.split("token=")[1];
  const acceptance = await Promise.allSettled([1, 2].map(() => invitations.accept(null, { token, name: "Invited fixture", password: "isolated-safe-password-12" })));
  assert.equal(acceptance.filter(result => result.status === "fulfilled").length, 1);
  const admission = await pool.query("SELECT * FROM account_admissions WHERE invitation_id=$1", [invite.invitation.id]); assert.equal(admission.rowCount, 1);
  const account = await pool.query("SELECT password FROM auth_accounts WHERE user_id=$1", [admission.rows[0].user_id]); assert.ok(account.rows[0].password); assert.notEqual(account.rows[0].password, "isolated-safe-password-12");
  const files = new Map<string, Uint8Array>(); const attachments = new Attachments(repo, { async put(key, bytes) { files.set(key, bytes); }, async remove(key) { files.delete(key); }, async get(key) { return new ReadableStream({ start(controller) { controller.enqueue(files.get(key)); controller.close(); } }); } });
  const file = await attachments.upload(owner.userId, workspace, other.id, null, "fixture.txt", new TextEncoder().encode("fixture"));
  assert.equal((await attachments.list(owner.userId, workspace, other.id))[0].id, file.id);
  const outbox = new EmailOutbox(repo, "isolated-pg-test-secret-at-least-32-characters");
  await outbox.enqueue({ to: owner.email, subject: "Test", text: "Fixture only", key: `pg:${suffix}` }, "reset", new Date(Date.now() + 60000).toISOString());
  let delivered = 0; await Promise.all([outbox.deliver({ async send() { delivered++; } }), outbox.deliver({ async send() { delivered++; } })]); assert.equal(delivered, 1);
});
